### PR TITLE
feat: add optional nanoid base models

### PR DESCRIPTION
**Pull request by winstxnhdw**
## Description

This PR adds an optional Nano ID base model integration.

### CODE REVIEW

**Comment by winstxnhdw** [comment]
Hey @cofin, could you check if this CI failure is related?

**Comment by cofin** [comment]
@winstxnhdw Thanks for this.  sorry i missed this over the weekend.  I'll take a look and review this as soon as i can.

**Comment by cofin** [comment]
you'll probably want to run `rm pdm.lock && make install`.  It'll generate a new lock for that includes the nanoid deps.

**Review by JacobCoffee — APPROVED** [review]
Could we have some usage documentation around this maybe? In general, adding bits via PR here and there would greatly reduce 1.0 stable releases burden

**Comment by winstxnhdw** [comment]
Definitely, but I am not sure where. There doesn’t seem to be any foundational structure for the docs yet.

**Pull request merged**
